version: "3.1"

services:
    www:
        build: .
        ports:
            - 8888:80
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.31
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: advertisements_manager
            MYSQL_USER: advertisements_manager
            MYSQL_PASSWORD: advertisements_manager
            MYSQL_ROOT_PASSWORD: advertisements_manager
        volumes:
            - ./:/docker-entrypoint-initdb.d
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8881:80
        environment:
            MYSQL_USER: advertisements_manager
            MYSQL_PASSWORD: advertisements_manager
            MYSQL_ROOT_PASSWORD: advertisements_manager
        networks:
            - default